name: casdoor_flutter_sdk_example
description: Example app of casdoor_flutter_sdk.
publish_to: none
version: 1.0.0

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  casdoor_flutter_sdk:
    path: ../
  desktop_webview_window: ^0.3.0

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
