name: Flutter CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test casdoor-flutter-sdk  on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-11]

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@4389e6cbc6cb8a4b18c628ff96ff90be0e926aa8 # v1.5.3
        with:
          flutter-version: "2.8.1"
      - name: Install dependencies
        run: flutter packages get
      - name: Analyze
        run: flutter analyze
      - name: Format
        run: flutter format --set-exit-if-changed .
      - name: Run tests
        run: flutter test --coverage
      - name: Upload coverage to Codecov
        if: startsWith(matrix.os, 'macos')
        uses: codecov/codecov-action@v1.0.6

  # release on Github and pub.dev
  publish:
    needs: test
    if: github.repository == 'casdoor/casdoor-flutter-sdk' && github.event_name == 'push'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: cedx/setup-dart@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm install -g "@semantic-release/changelog"
      - run: npm install -g "@semantic-release/git"
      - run: npm install -g "pub-semantic-release"

      - name: Semantic Release
        run: |
          export NODE_PATH="$(npm root -g)"
          npx semantic-release@17
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN  }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Publish Dart/Flutter package
        uses: k-paxian/dart-package-publisher@master
        with:
            flutter: true
            skipTests: true
            credentialJson: ${{ secrets.CREDENTIAL_JSON }}
